import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@fontsource-variable/inter";

export const metadata = {
  title: "BAC | Inbox Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
